Quicksort: Quicksort.o
	g++ Quicksort.o -o quick
	
Quicksort.o: Quicksort.cpp
	g++ -c Quicksort.cpp

InsertionSort: InsertionSort.o
	g++ InsertionSort.o -o insertion
	
InsertionSort.o: InsertionSort.cpp
	g++ -c InsertionSort.cpp

Freetext: Freetext.o
	g++ Freetext.o -o free
	
Freetext.o: Freetext.cpp
	g++ -c Freetext.cpp